namespace TestBuilderGenerator;

public static class CodeTemplates
{
    private const string NamespaceName = "TestBuilderGenerator";
    public const string AttributeClassName = "BuilderGenOfAttribute";

    public const string AttributeIdentifier = $"{NamespaceName}.{AttributeClassName}`1";
    public const string AttributeTemplate =
        $$"""
        // <auto-generated/>
        // lang=c#
        
        #nullable enable
        
        namespace {{NamespaceName}};

        [global::System.CodeDom.Compiler.GeneratedCode("TestBuilderGenerator", "1.0.0.0")]
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
        internal sealed class {{AttributeClassName}}<T> : global::System.Attribute
        {
        }
        
        // </auto-generated/>
        """;
}
