using System;
using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TestBuilderGenerator;

[Generator(LanguageNames.CSharp)]
public class Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(PostInitializationCallback);

        // TODO: DONT UPDATE WHEN NO CHANGES
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                CodeTemplates.AttributeIdentifier,
                SyntaxProviderPredicate,
                SyntaxProviderTransform)
            .WithComparer(GenerationDataComparer.Instance)
            .Collect();

        context.RegisterSourceOutput(provider, Execute);
    }

    private void Execute(SourceProductionContext context, ImmutableArray<GenerationData> generationData)
    {
        var sb = new StringBuilder();
        var writer = new StringWriter(sb);
        using var indentWriter = new IndentedTextWriter(writer);

        foreach (var data in generationData)
        {
            indentWriter.WriteLine("// <auto-generated/>");
            indentWriter.WriteLine("// lang=c#");
            // TODO: Set by config
            // indentWriter.WriteLine($"// Generated At {DateTime.UtcNow} UTC");
            indentWriter.WriteLine("#nullable enable");
            indentWriter.WriteLine("#pragma warning disable CA5394");

            if (!data.Builder.Namespace.IsGlobalNamespace)
            {
                // TODO: not file scoped namespaces
                indentWriter.WriteLine($"namespace {data.Builder.Namespace.FullName};");
                indentWriter.WriteLine();
            }

            var builderIdentifier = data.Builder.Name;
            var accessibility = data.Builder.Modifiers.First(x =>
                x.IsKind(SyntaxKind.PublicKeyword) ||
                x.IsKind(SyntaxKind.InternalKeyword));

            indentWriter.WriteLine($"{accessibility} partial class {builderIdentifier}");
            indentWriter.WriteLine("{");
            indentWriter.Indent++;

            var builderProperties = data.Builder.Properties;

            var builderMethods = data.Builder.Methods;

            var properties = data.TargetClass.Properties;

            foreach (var property in properties)
            {
                var propertyName = property.Name;
                var propertyType = property.Type;

                var variableName = propertyName.ToCamelCase();
                var fieldName = $"_{variableName}";

#pragma warning disable S125

                // EXPERIMENTAL
                // indentWriter.WriteLine($"public partial {fixedPropertyType} Default{propertyName} {{ get; }}");
#pragma warning restore S125

                var defaultPropertyName = $"Default{data.TargetClass.Name}{propertyName}";
                var hasAlreadyDefinedDefaultProperty =
                    builderProperties.Any(x => x.Name == defaultPropertyName);
                if (!hasAlreadyDefinedDefaultProperty)
                {
                    indentWriter.Write($"public static {propertyType} {defaultPropertyName} {{ get; }} = ");
                    switch (propertyType)
                    {
                        case nameof(Guid):
                            indentWriter.WriteLine("global::System.Guid.NewGuid();");
                            break;
                        case "int":
                        case nameof(Int32):
                            indentWriter.WriteLine("global::System.Random.Shared.Next();");
                            break;
                        case "long":
                        case nameof(Int64):
                            indentWriter.WriteLine("global::System.Random.Shared.NextInt64();");
                            break;
                        case "float":
                        case nameof(Single):
                            indentWriter.WriteLine("global::System.Random.Shared.NextSingle();");
                            break;
                        case "double":
                        case nameof(Double):
                            indentWriter.WriteLine("global::System.Random.Shared.NextDouble();");
                            break;
                        case "string":
                        case nameof(String) when property.NullableAnnotation != NullableAnnotation.Annotated:
                            indentWriter.WriteLine($"\"{defaultPropertyName}\";");
                            break;
                        case nameof(DateTime):
                            indentWriter.WriteLine("global::System.DateTime.UtcNow;");
                            break;
                        case nameof(DateTimeOffset):
                            indentWriter.WriteLine("global::System.DateTimeOffset.UtcNow;");
                            break;
                        case not null when property.IsCollectionType:
                            indentWriter.WriteLine("[];");
                            break;
                        default:
                            indentWriter.WriteLine("default;");
                            break;
                    }
                }

                indentWriter.WriteLine($"private {propertyType} {fieldName} = {defaultPropertyName};");
                var methodName = $"With{propertyName}";
                var hasAlreadyDefinedMethod = builderMethods.Any(x => x.Name == methodName);
                if (!hasAlreadyDefinedMethod)
                {
                    indentWriter.WriteLine(
                        $"public {builderIdentifier} {methodName}({propertyType} {variableName})");
                    indentWriter.WriteLine("{");
                    indentWriter.Indent++;

                    indentWriter.WriteLine($"{fieldName} = {variableName};");
                    indentWriter.WriteLine("return this;");

                    indentWriter.Indent--;
                    indentWriter.WriteLine("}");
                }

                indentWriter.WriteLineNoTabs(string.Empty);
            }

            indentWriter.WriteLine($"public static {builderIdentifier} Default => new {builderIdentifier}();");
            indentWriter.WriteLine($"public partial {data.TargetClass.Identity} Build();");

            indentWriter.Indent--;
            indentWriter.WriteLine("}");

            indentWriter.WriteLine();
            indentWriter.Write("// </auto-generated>");

            context.AddSource($"{data.Builder.Name}.g.cs", sb.ToString());
            sb.Clear();
        }
    }

    // TODO: handle records
    private static GenerationData SyntaxProviderTransform(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        // CHECK IF MORE ATTRIBUTES
        // TODO: pass by typeof
        var targetType = context.Attributes.First().AttributeClass.TypeArguments.First();
        var classDeclaration = context.TargetNode as ClassDeclarationSyntax;

        var builderNamespace = new NamespaceInfo(context.TargetSymbol.ContainingNamespace);
        var builderProperties = classDeclaration.Members.OfType<PropertyDeclarationSyntax>()
            .Select(PropertyInfo.FromDeclarationSyntax)
            .ToArray();
        var builderMethods = classDeclaration.Members.OfType<MethodDeclarationSyntax>()
            .Select(MethodInfo.FromDeclarationSyntax)
            .ToArray();

        var builderInfo = new BuilderInformation(
            builderNamespace,
            builderProperties,
            builderMethods,
            classDeclaration.Identifier.ValueText,
            classDeclaration.Modifiers);

        var targetClassNamespace = new NamespaceInfo(targetType.ContainingNamespace);
        var targetClassProperties = targetType.GetMembers().OfType<IPropertySymbol>()
            .Select(SymbolPropertyInfo.FromSymbol)
            .ToArray();
        var targetClassMethods = targetType.GetMembers().OfType<IMethodSymbol>()
            .Select(MethodInfo.FromSymbol)
            .ToArray();

        var classInfo = new TargetClassInformation(
            targetClassNamespace,
            targetClassProperties,
            targetClassMethods,
            targetType.ToDisplayString(),
            targetType.MetadataName);

        return new GenerationData(builderInfo, classInfo);
    }

    private static bool SyntaxProviderPredicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
    {
        return syntaxNode is ClassDeclarationSyntax;
    }

    private static void PostInitializationCallback(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource($"{CodeTemplates.AttributeClassName}.g.cs", CodeTemplates.AttributeTemplate);
    }
}
