name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to Deploy
        required: true
        type: string
      run_id:
        description: Run id where artifacts are stored
        required: true
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Publish ${{inputs.version}} nuget version

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: "${{ inputs.version }}-artifacts"
          run-id: '${{ inputs.run_id }}'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to nuget org
        run: dotnet nuget push TestBuilderGenerator.${{ inputs.version }}.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source "github" --skip-duplicate
